// pages/index.tsx (Landing Page)
import Head from "next/head";
import Header from "@/pages/components/Header"; // Sesuaikan path import
import Footer from "@/pages/components/Footer"; // Sesuaikan path import
import Main from "@/pages/landingpage/Main";
import style from "@/styles/landingpage/global.module.css";
import { useEffect } from "react";
import Cookies from 'js-cookie'; // Tambahkan ini untuk menangani cookie

const Index: React.FC = () => {
  useEffect(() => {
    const isLoggedIn = Cookies.get("isLoggedIn");

    Cookies.remove("isLoggedIn");
  }, []);

  return (
    <>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={style.layoutContainer}>
        <Header />
        <Main />
        <Footer />
      </div>
    </>
  );
};

export default Index;
