import Head from "next/head";
import Header from "@/pages/components/Header"; 
import Footer from "@/pages/components/Footer"; 
import Main from "@/pages/chatbot/Main";
import { useRouter } from "next/router"; 
import style from "@/styles/landingpage/global.module.css";
import { useEffect, useState } from "react";
import Cookies from 'js-cookie';

const Index: React.FC = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const Router = useRouter();
  useEffect(() => {
    const isLoggedIn = Cookies.get("isLoggedIn");
    if (!isLoggedIn) {
      Router.push("/landingpage");
    }
  });
  return (
    <>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={style.layoutContainer}>
        <Header/>
        <Main />
        <Footer />
      </div>
    </>
  );
};

export default Index;
