// pages/index.tsx (Landing Page)
import Head from "next/head";
import Header from "@/pages/components/Header"; // Sesuaikan path import
import Footer from "@/pages/components/Footer"; // Sesuaikan path import
import Main from "@/pages/chatbot/Main";
import style from "@/styles/landingpage/global.module.css";
import { useEffect, useState } from "react";

const Index: React.FC = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    // Hapus status login dari localStorage saat kembali ke landing page
    localStorage.removeItem("isLoggedIn");
    setIsLoggedIn(false); // Atur status login menjadi false
  }, []);

  return (
    <>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={style.layoutContainer}>
        <Header isLoggedIn={isLoggedIn} />
        <Main />
        <Footer />
      </div>
    </>
  );
};

export default Index;
